### ISSUE TITLE
Native VCC support for MaterialReplacer

### ISSUE THREAD

**Issue by jerryzmtz** [kurotu/MaterialReplacer#1]
Could you add VCC support? The latest version is 1.2.0 but there is a legacy version included in VRCQuest Tool VCC, which causes problems.

**Comment by kurotu** [comment]
What do you mean "VCC support"? The tools is already provided via my vpm repository. https://kurotu.github.io/vpm-repos/
(Sorry to not announced in readme.)
By the way, Material Replacer is now a part of new tool, [KRT Material Tools](https://github.com/kurotu/krt-material-tools). It's recommended to get future updates.

> there is a legacy version included in VRCQuest Tool VCC, which causes problems.

Sadly I'm not sure what is your problem. Please describe in detail if it's a bug report.

**Comment by jerryzmtz** [comment]
> What do you mean "VCC support"? The tools is already provided via my vpm repository. https://kurotu.github.io/vpm-repos/ (Sorry to not announced in readme.) By the way, Material Replacer is now a part of new tool, [KRT Material Tools](https://github.com/kurotu/krt-material-tools). It's recommended to get future updates.
> 
> > there is a legacy version included in VRCQuest Tool VCC, which causes problems.
> 
> Sadly I'm not sure what is your problem. Please describe in detail if it's a bug report.

I have not KRT material Tools could be added from your vpm repository. I want you to update material replacer to 1.2.0 so that I could update it through VCC instead of import the unity package. Given that KRT material Tools could replace material, I have no further problems. Thank you a lot!

**Comment by kurotu** [comment]
I have noticed that 1.2.0 was not included to the vpm repository. Thanks to let me know.

KRT Material Tools' material replacer is just an equivalent of the original material replacer. Feel free to make issues when you meet problem.
